name: Scala Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Eclipse Temurin - JDK 20
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Test
        run: sbt test
