on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

name: Scala Update

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Update
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_SCALA_UPDATE_ID }}
          private_key: ${{ secrets.APP_SCALA_UPDATE_PK }}

      - name: Scala Update
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
